# -*- coding: utf-8 -*-
"""Prueba shared drive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15EZFT3owowYbtVRciNC__OUgnJIJD5rI
"""

!pip install pydrive
!pip install googledrivedownloader

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Autenticación de cuenta de Google Drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

import os
from google.colab import auth
from googleapiclient.discovery import build

# Autenticación de cuenta de Google Drive
auth.authenticate_user()
drive_service = build('drive', 'v3')

# ID de la carpeta compartida
folder_id = "1fHhS2KZGEYME0buBqtwmMxDuaMbsgvF2"

# Obtener lista de archivos en la carpeta compartida
results = drive_service.files().list(q=f"'{folder_id}' in parents", fields="files(id, name, mimeType)").execute()
files = results.get('files', [])

# Descargar archivos CSV de la carpeta compartida
for file in files:
    file_id = file['id']
    file_name = file['name']
    mime_type = file['mimeType']

    if mime_type == 'text/csv':
        # Descargar archivos CSV
        request = drive_service.files().get_media(fileId=file_id)
        with open(os.path.join('/content', file_name), 'wb') as f:
            f.write(request.execute())
            print(f"Archivo CSV descargado: {file_name}")